-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 16:25:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pi_meninadossapatos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pi_meninadossapatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pi_meninadossapatos` DEFAULT CHARACTER SET utf8 ;
USE `pi_meninadossapatos` ;

-- -----------------------------------------------------
-- Table `pi_meninadossapatos`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_meninadossapatos`.`login` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_meninadossapatos`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_meninadossapatos`.`perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cpf` INT NULL,
  `data_nascimento` DATE NULL,
  `celular` VARCHAR(45) NULL,
  `telefone_fixo` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `login_id_login` INT NOT NULL,
  PRIMARY KEY (`id_perfil`, `login_id_login`),
  INDEX `fk_perfil_login1_idx` (`login_id_login` ASC),
  CONSTRAINT `fk_perfil_login1`
    FOREIGN KEY (`login_id_login`)
    REFERENCES `pi_meninadossapatos`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_meninadossapatos`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_meninadossapatos`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `codigo_sku` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `preco` INT NULL,
  `cor` VARCHAR(45) NULL,
  `imagem` VARCHAR(45) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_meninadossapatos`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_meninadossapatos`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `endereço_entrega` VARCHAR(45) NULL,
  `opcao_entrega` VARCHAR(45) NULL,
  `forma_pagamento` VARCHAR(45) NULL,
  `perfil_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `perfil_id_perfil`),
  INDEX `fk_Pedido_perfil2_idx` (`perfil_id_perfil` ASC),
  CONSTRAINT `fk_Pedido_perfil2`
    FOREIGN KEY (`perfil_id_perfil`)
    REFERENCES `pi_meninadossapatos`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_meninadossapatos`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_meninadossapatos`.`estoque` (
  `id_estoque` INT NOT NULL AUTO_INCREMENT,
  `numeracao` VARCHAR(45) NULL,
  `quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_meninadossapatos`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_meninadossapatos`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_meninadossapatos`.`endereco_has_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_meninadossapatos`.`endereco_has_perfil` (
  `endereco_id_endereco` INT NOT NULL,
  `perfil_id_perfil` INT NOT NULL,
  PRIMARY KEY (`endereco_id_endereco`, `perfil_id_perfil`),
  INDEX `fk_endereco_has_perfil_perfil1_idx` (`perfil_id_perfil` ASC),
  INDEX `fk_endereco_has_perfil_endereco1_idx` (`endereco_id_endereco` ASC),
  CONSTRAINT `fk_endereco_has_perfil_endereco1`
    FOREIGN KEY (`endereco_id_endereco`)
    REFERENCES `pi_meninadossapatos`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_has_perfil_perfil1`
    FOREIGN KEY (`perfil_id_perfil`)
    REFERENCES `pi_meninadossapatos`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_meninadossapatos`.`produto_has_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_meninadossapatos`.`produto_has_estoque` (
  `produto_id_produto` INT NOT NULL,
  `estoque_id_estoque` INT NOT NULL,
  PRIMARY KEY (`produto_id_produto`, `estoque_id_estoque`),
  INDEX `fk_produto_has_estoque_estoque1_idx` (`estoque_id_estoque` ASC),
  INDEX `fk_produto_has_estoque_produto1_idx` (`produto_id_produto` ASC),
  CONSTRAINT `fk_produto_has_estoque_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `pi_meninadossapatos`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_estoque_estoque1`
    FOREIGN KEY (`estoque_id_estoque`)
    REFERENCES `pi_meninadossapatos`.`estoque` (`id_estoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_meninadossapatos`.`produto_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_meninadossapatos`.`produto_has_pedido` (
  `produto_id_produto` INT NOT NULL,
  `pedido_id_pedido` INT NOT NULL,
  `quantidade` VARCHAR(45) NULL,
  `numeracao` VARCHAR(45) NULL,
  PRIMARY KEY (`produto_id_produto`, `pedido_id_pedido`),
  INDEX `fk_produto_has_Pedido_Pedido1_idx` (`pedido_id_pedido` ASC),
  INDEX `fk_produto_has_Pedido_produto1_idx` (`produto_id_produto` ASC),
  CONSTRAINT `fk_produto_has_Pedido_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `pi_meninadossapatos`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_Pedido_Pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `pi_meninadossapatos`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
